/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { publicModelPath } from "../../../config/3d-model.config";
import { RigidBody } from "@react-three/rapier";
import { JSX } from "react";
import { Mesh } from "three";

const path = publicModelPath("high_build_stairs.glb");

type Props = JSX.IntrinsicElements["group"] & {};

export default function Stairs(props: Props) {
  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -24.393, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs001 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -23.547, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs002 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -22.564, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs003 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -21.717, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs004 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -20.729, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs005 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -19.883, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs006 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -18.9, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs007 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -18.052, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs008 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -17.067, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs009 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -16.221, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs010 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -15.238, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs011 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -14.391, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs012 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -13.403, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs013 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -11.574, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs014 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -10.727, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs015 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -9.74, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs016 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -8.895, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs017 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -7.912, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs018 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -7.064, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs019 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -6.076, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs020 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -5.23, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs021 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -4.247, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs022 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, -3.4, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs023 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, -2.415, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs024 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -1.569, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs025 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, -0.586, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs026 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, 0.262, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs027 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, 1.249, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs028 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.867, 3.078, -0.386]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs029 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[12.974, 3.926, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs030 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[15.8, 4.913, 1.629]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs031 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, -12.558, 0.623]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs032 as Mesh).geometry}
          material={materials["Material.025"]}
          position={[18.696, 2.094, 0.623]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload(path);
