/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { JSX } from "react";
import { publicModelPath } from "../../../config/3d-model.config";

type Props = JSX.IntrinsicElements["group"] & {};

const path = publicModelPath("house_assets.glb");
export default function ApartmentBuilding({ ...props }: Props) {
  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bed.geometry}
        material={materials.DefaultMaterial}
        position={[0.889, 1.101, -3.237]}
        rotation={[0, 0.05, 0]}
        scale={1.654}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.021"]}
        position={[-0.636, 1.21, -1.178]}
        scale={[0.029, 0.097, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.021"]}
        position={[1.235, 1.21, -1.172]}
        scale={[0.029, 0.097, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.021"]}
        position={[-0.642, 1.21, -4.61]}
        scale={[0.029, 0.097, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.021"]}
        position={[1.218, 1.21, -4.616]}
        scale={[0.029, 0.097, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.grey}
        position={[0.293, 1.432, -2.899]}
        scale={[1, 0.143, 1.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.light_grey}
        position={[0.694, 1.627, -2.339]}
        rotation={[0, 0.176, 0]}
        scale={[1.005, 0.023, 1.547]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["white.001"]}
        position={[-0.193, 1.616, -4.395]}
        scale={[0.42, 0.06, 0.264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["white.001"]}
        position={[0.817, 1.595, -4.39]}
        rotation={[0, 0.116, 0]}
        scale={[0.42, 0.06, 0.264]}
      />
      <group
        position={[-7.073, 1.414, 0.414]}
        rotation={[0.063, -0.289, 0.796]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[-7.162, 1.138, 1.042]}
        rotation={[0.063, -0.289, 0.796]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan001_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan001_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan001_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[-7.346, 1.158, 1.799]}
        rotation={[3.03, -1.004, -2.458]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan002_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan002_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan002_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[-6.615, 1.221, -1.592]}
        rotation={[3.03, -1.004, -2.458]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan003_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan003_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan003_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[-1.114, 1.123, -4.137]}
        rotation={[1.591, 0.003, 2.362]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan004_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan004_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan004_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[-0.911, 1.124, -4.627]}
        rotation={[1.591, 0.003, 2.362]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan005_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan005_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan005_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[3.127, 1.12, -3.899]}
        rotation={[1.591, 0.003, 2.362]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan006_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan006_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan006_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <group
        position={[2.415, 1.137, -1.399]}
        rotation={[2.726, -0.218, 1.502]}
        scale={0.022}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan007_1.geometry}
          material={materials.sidemate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan007_2.geometry}
          material={materials.bottommate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ColaCan007_3.geometry}
          material={materials.topmatw}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wooden_shelf.geometry}
        material={materials["Material.022"]}
        position={[-7.338, 1.135, 2.534]}
        rotation={[0, 0.071, 0]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wooden_shelf001.geometry}
        material={materials["Material.022"]}
        position={[-5.597, 1.14, 3.893]}
        rotation={[0, 1.485, 0]}
        scale={[0.007, 0.007, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walkdude_01.geometry}
        material={materials.white}
        position={[-5.98, 2.256, -2.738]}
        rotation={[3.113, -1.05, 0.62]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walkdude_01002.geometry}
        material={materials.white}
        position={[-5.943, 2.401, -2.003]}
        rotation={[-3.015, 0.27, -0.469]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.fridge}
        position={[3.881, 2.697, -4.075]}
        rotation={[Math.PI / 2, 0, 0.928]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.fridge}
        position={[3.553, 1.85, -4.259]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Books.geometry}
        material={nodes.Books.material}
        position={[-6.183, 2.32, -0.337]}
        rotation={[0, 0.764, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cell_phone.geometry}
        material={nodes.Cell_phone.material}
        position={[-6.143, 2.245, -2.497]}
        rotation={[0, -0.618, 0]}
        scale={0.633}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Books001.geometry}
        material={nodes.Books001.material}
        position={[-6.176, 2.269, -0.333]}
        rotation={[0, 1.112, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Books002.geometry}
        material={nodes.Books002.material}
        position={[-4.552, 2.385, -3.669]}
        rotation={[0, -0.671, 0]}
      />
      <group
        position={[-5.632, 1.557, -1.957]}
        rotation={[Math.PI, -1.302, Math.PI]}
        scale={0.153}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.char001.geometry}
        material={materials["Material.006"]}
        position={[-5.632, 1.557, -1.957]}
        rotation={[Math.PI, -1.302, Math.PI]}
        scale={0.153}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.char002.geometry}
        material={materials["Material.006"]}
        position={[-5.632, 1.557, -1.957]}
        rotation={[Math.PI, -1.302, Math.PI]}
        scale={0.153}
      />
      <group
        position={[-6.733, 2.42, -2.087]}
        rotation={[0, -0.134, -Math.PI / 2]}
        scale={[0.162, 0.014, 0.26]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040_1.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <group
        position={[-6.754, 2.258, -1.825]}
        rotation={[0, -0.134, -1.185]}
        scale={[0.193, 0.014, 0.26]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_1.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Eraser.geometry}
        material={nodes.Eraser.material}
        position={[-6.606, 2.241, -0.679]}
        rotation={[0, -0.819, 0]}
        scale={0.272}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dish.geometry}
        material={nodes.Dish.material}
        position={[-4.751, 2.424, -3.399]}
        scale={0.738}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes001.geometry}
        material={materials["black.003"]}
        position={[-7.013, 2.3, -0.606]}
        scale={0.514}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes002.geometry}
        material={materials.black_light}
        position={[-6.584, 2.295, -2.754]}
        rotation={[Math.PI, -1.27, Math.PI]}
        scale={0.424}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes003.geometry}
        material={materials["black.003"]}
        position={[-7.033, 1.437, 0.18]}
        scale={2.688}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes004.geometry}
        material={materials["Material.019"]}
        position={[-6.94, 1.289, 0.18]}
        rotation={[1.799, 0, 0]}
        scale={0.556}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes005.geometry}
        material={materials["Material.019"]}
        position={[-7.183, 1.311, 0.136]}
        rotation={[1.727, 0.167, 0.813]}
        scale={0.556}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes006.geometry}
        material={materials["Material.019"]}
        position={[-7.511, 1.174, 0.591]}
        rotation={[1.641, 0.048, 0.84]}
        scale={0.556}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Boxes007.geometry}
        material={materials["Material.019"]}
        position={[-7.43, 1.177, -0.712]}
        rotation={[1.641, 0.048, 0.84]}
        scale={0.556}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dish001.geometry}
        material={nodes.Dish001.material}
        position={[-4.751, 2.424, -3.399]}
        scale={0.738}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dish002.geometry}
        material={nodes.Dish002.material}
        position={[-0.887, 1.153, -4.403]}
        rotation={[-0.076, 0.025, 0.08]}
        scale={0.738}
      />
      <group position={[-6.512, 1.01, -1.962]} scale={0.6}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials.grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials["white.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper.geometry}
        material={materials.Paper}
        position={[-6.631, 2.239, -0.8]}
        rotation={[0, 1.131, 0]}
        scale={0.47}
      />
      <group position={[-6.892, 2.42, -1.022]} rotation={[0, 1.183, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={nodes.Cube027_1.material}
        />
      </group>
      <group
        position={[-3.846, 2.495, -3.979]}
        rotation={[0, -1.554, 0]}
        scale={0.726}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials.white}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen.geometry}
        material={nodes.Pen.material}
        position={[-7.019, 2.361, -0.58]}
        rotation={[-0.716, 0.479, 2.323]}
        scale={0.601}
      />
      <group
        position={[-3.918, 1.116, -3.84]}
        rotation={[0, -1.45, 0]}
        scale={0.6}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials.grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials["white.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper001.geometry}
        material={materials.Paper}
        position={[-6.78, 2.238, -2.686]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper002.geometry}
        material={materials.Paper}
        position={[-6.788, 2.237, -2.493]}
        rotation={[0, -0.281, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper003.geometry}
        material={materials.Paper}
        position={[-6.386, 2.24, -0.633]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper004.geometry}
        material={materials.Paper}
        position={[-6.733, 2.24, -2.587]}
        rotation={[0, -0.281, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper005.geometry}
        material={materials.Paper}
        position={[-6.627, 1.154, -0.526]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper006.geometry}
        material={materials.Paper}
        position={[-7.353, 1.154, 0.799]}
        rotation={[3.033, 0.775, 0.071]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper007.geometry}
        material={materials.Paper}
        position={[-7.227, 1.149, 0.7]}
        rotation={[0.061, 0.493, 2.719]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper008.geometry}
        material={materials.Paper}
        position={[-7.066, 1.29, 0.196]}
        rotation={[2.423, 0.876, 0.58]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper009.geometry}
        material={materials.Paper}
        position={[-6.891, 1.313, 0.093]}
        rotation={[2.423, 0.876, 0.58]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper010.geometry}
        material={materials.Paper}
        position={[-7.049, 1.414, 0.104]}
        rotation={[2.423, 0.876, 0.58]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper011.geometry}
        material={materials.Paper}
        position={[-6.972, 1.388, 0.266]}
        rotation={[2.423, 0.876, 0.58]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper012.geometry}
        material={materials.Paper}
        position={[-7.153, 1.284, 0.282]}
        rotation={[2.423, 0.876, 0.58]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper013.geometry}
        material={materials.Paper}
        position={[-4.395, 2.389, -4.062]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper014.geometry}
        material={materials.Paper}
        position={[-5.241, 1.154, -4.211]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper015.geometry}
        material={materials.Paper}
        position={[-4.72, 1.154, -4.37]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper016.geometry}
        material={materials.Paper}
        position={[-6.036, 1.154, -4.215]}
        rotation={[0, 0.725, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper017.geometry}
        material={materials.Paper}
        position={[-3.442, 1.149, -4.294]}
        rotation={[0.061, 0.493, 2.719]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper018.geometry}
        material={materials.Paper}
        position={[-5.552, 1.149, -4.456]}
        rotation={[0.061, 0.493, 2.719]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper019.geometry}
        material={materials.Paper}
        position={[-4.29, 2.364, -4.106]}
        rotation={[0, -0.962, 0]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper020.geometry}
        material={materials.Paper}
        position={[-4.544, 2.388, -4.164]}
        rotation={[-0.342, -0.997, -0.327]}
        scale={0.47}
      />
      <group
        position={[-4.954, 2.455, -3.664]}
        rotation={[0, -1.078, 0]}
        scale={0.621}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042_1.geometry}
          material={nodes.Cube042_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen001.geometry}
        material={nodes.Pen001.material}
        position={[-6.966, 2.361, -0.606]}
        rotation={[-1.871, 0.915, -2.398]}
        scale={0.601}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen002.geometry}
        material={nodes.Pen002.material}
        position={[-7.057, 2.361, -0.607]}
        rotation={[-0.771, -0.581, 1.451]}
        scale={0.601}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen003.geometry}
        material={nodes.Pen003.material}
        position={[-6.697, 2.241, -0.704]}
        rotation={[0.311, -0.22, 2.808]}
        scale={0.601}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen004.geometry}
        material={nodes.Pen004.material}
        position={[-6.966, 2.244, -1.526]}
        rotation={[2.656, -0.877, -0.789]}
        scale={0.601}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_LP_Final.geometry}
        material={materials.window_2}
        position={[-7.753, 2.617, -0.207]}
        rotation={[Math.PI / 2, 0, 1.596]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_LP_Final003.geometry}
        material={materials.window_2}
        position={[-7.753, 2.231, -0.207]}
        rotation={[Math.PI / 2, 0, 1.596]}
        scale={[0.21, 0.21, 0.201]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["black.002"]}
        position={[0.963, 5.661, 0.422]}
        scale={[0.108, 0.068, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.962, 5.351, 0.421]}
        scale={[0.006, 0.287, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.963, 5.592, 0.422]}
        scale={[0.042, 0.026, 0.042]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.963, 5.079, 0.422]}
        scale={[0.033, 0.021, 0.033]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fun_blades.geometry}
        material={materials["Material.002"]}
        position={[0.963, 5.058, 0.422]}
        rotation={[-Math.PI, 0.863, -Math.PI]}
        scale={[0.644, 0.011, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloppyDisk_Black.geometry}
        material={materials.M_FloppyDisk}
        position={[-6.898, 2.239, -2.95]}
        rotation={[0, 0, -0.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloppyDisk_Blue.geometry}
        material={materials.M_FloppyDisk}
        position={[-6.677, 2.243, -3.144]}
        rotation={[0, 1.049, -0.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloppyDisk_Green.geometry}
        material={materials.M_FloppyDisk}
        position={[-6.706, 2.238, -2.947]}
        rotation={[-Math.PI, 0.958, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloppyDisk_Red.geometry}
        material={materials.M_FloppyDisk}
        position={[-6.716, 2.243, -3.077]}
        rotation={[0, 1.485, -0.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroComputer.geometry}
        material={materials.M_RetroComputer}
        position={[-6.626, 1.133, -3.402]}
        rotation={[0, 1.452, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroKeyboard.geometry}
        material={materials.M_RetroKeyboardMouse}
        position={[-6.24, 2.236, -2.968]}
        rotation={[0, 1.182, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroMonitor.geometry}
        material={materials.M_RetroMonitor}
        position={[-6.818, 2.232, -3.45]}
        rotation={[0, 0.854, 0]}
        scale={1.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroMouse.geometry}
        material={materials.M_RetroKeyboardMouse}
        position={[-6.072, 2.342, -3.367]}
        rotation={[0, 1.23, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroMonitor001.geometry}
        material={materials.M_RetroMonitor}
        position={[-7.114, 1.013, -4.229]}
        rotation={[Math.PI, -1.525, Math.PI]}
        scale={1.224}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroComputer001.geometry}
        material={materials.M_RetroComputer}
        position={[-5.06, 2.478, -4.014]}
        rotation={[-3.093, 0.03, 1.566]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroComputer002.geometry}
        material={materials.M_RetroComputer}
        position={[-5.6, 2.709, -4.095]}
        rotation={[0.028, -0.198, -1.558]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroKeyboard001.geometry}
        material={materials.M_RetroKeyboardMouse}
        position={[-4.799, 2.586, -4.076]}
        rotation={[-0.046, -0.197, 2.138]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RetroKeyboard002.geometry}
        material={materials.M_RetroKeyboardMouse}
        position={[-5.33, 2.832, -3.951]}
        rotation={[0.021, 0.141, -0.022]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["wall.001"]}
        position={[0.072, 1.12, 0]}
        scale={[7.847, 4.749, 4.749]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.brown}
        position={[0.071, 1.12, 0]}
        scale={[7.847, 4.749, 4.749]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["wall.001"]}
        position={[0.082, 1.12, 0]}
        scale={[7.847, 4.749, 4.749]}
      />
      <group position={[-0.003, -25.458, 10.826]} scale={1.56}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh015.geometry}
          material={materials["Brownstone_Facade_Flr_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh015_1.geometry}
          material={materials["Brownstone_Facade_FLR_7.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh015_2.geometry}
          material={materials["Brownstone_Maskedstuff_1.002"]}
        />
      </group>
      <group position={[-0.003, -25.458, 10.826]} scale={1.56}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017.geometry}
          material={materials["Brownstone_Facade_Flr_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_1.geometry}
          material={materials["Brownstone_Facade_FLR_7.001"]}
        />
      </group>
      <group
        position={[8.686, -25.285, 26.141]}
        rotation={[0, -0.202, 0]}
        scale={1.56}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh018.geometry}
          material={materials["Brownstone_Facade_Flr_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh018_1.geometry}
          material={materials["Brownstone_Facade_FLR_7.001"]}
        />
      </group>
      <group
        position={[11.205, -25.285, 26.141]}
        rotation={[0, 0.352, 0]}
        scale={1.56}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh019.geometry}
          material={materials["Brownstone_Facade_Flr_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh019_1.geometry}
          material={materials["Brownstone_Facade_FLR_7.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_side_build.geometry}
        material={materials["Brownstone_Facade_Flr_1.001"]}
        position={[-0.003, -25.458, 10.826]}
        scale={1.56}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_side_build.geometry}
        material={materials["Brownstone_Facade_Flr_1.001"]}
        position={[-0.003, -25.458, 10.826]}
        scale={1.56}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_side_build.geometry}
        material={materials["Brownstone_Facade_Flr_1.001"]}
        position={[-0.003, -25.458, 10.826]}
        scale={1.56}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["top-side_build"].geometry}
        material={materials["Brownstone_Facade_Flr_1.001"]}
        position={[-0.003, -25.458, 10.826]}
        scale={1.56}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Damage_Door_Frame.geometry}
        material={materials.Door_Material}
        position={[7.926, 2.282, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.011, 0.011, 0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Damage_Door_Door.geometry}
        material={materials.Door_Material}
        position={[7.943, 1.122, -0.974]}
        rotation={[Math.PI / 2, 0, 1.777]}
        scale={[0.011, 0.011, 0.012]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Damage_Door_Handle.geometry}
          material={materials.Door_Material}
          position={[-6.701, -112.536, -85.819]}
          rotation={[0, 0, -Math.PI]}
          scale={[1.013, 1.013, 0.901]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Damage_Door_Handle002.geometry}
          material={materials.Door_Material}
          position={[4.589, -112.478, -85.903]}
          rotation={[0, 0, -Math.PI]}
          scale={[1.013, 1.013, 0.901]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.023"]}
        position={[10.9, 1.13, 0.149]}
        scale={[2.974, 1, 4.934]}
      />
      <group position={[13.852, 1.031, -0.81]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -1.852, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -4.755, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6002_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -7.662, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6003_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -10.565, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6004_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -13.469, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6005_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -16.38, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6006_6.geometry}
          material={materials.Wood}
        />
      </group>
      <group position={[13.848, -22.208, -0.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008.geometry}
          material={materials.Wood_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_1.geometry}
          material={materials.Wood_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_2.geometry}
          material={materials["Wood_2-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_3.geometry}
          material={materials.Wood_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_4.geometry}
          material={materials["Wood_2-3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_5.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6008_6.geometry}
          material={materials.Wood}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[13.868, 1.136, -0.797]}
        scale={[0.594, 0.854, 1.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[14.306, 1.523, -1.228]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[15.139, 1.396, 0.328]}
        rotation={[-0.77, -1.566, -2.305]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[15.139, 1.396, -0.742]}
        rotation={[-0.77, -1.566, -2.305]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[16.467, -0.029, -1.951]}
        rotation={[-2.379, 1.566, 0.844]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[16.467, -0.029, -0.881]}
        rotation={[-2.379, 1.566, 0.844]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[13.868, -1.745, -0.797]}
        scale={[0.594, 0.854, 1.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[15.139, -1.485, 0.328]}
        rotation={[-0.77, -1.566, -2.305]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[15.139, -1.485, -0.742]}
        rotation={[-0.77, -1.566, -2.305]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[16.467, -2.909, -1.951]}
        rotation={[-2.379, 1.566, 0.844]}
        scale={[0.378, 0.543, 0.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[16.467, -2.909, -0.881]}
        rotation={[-2.379, 1.566, 0.844]}
        scale={[0.378, 0.543, 0.801]}
      />
    </group>
  );
}

useGLTF.preload(path);
