/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { JSX } from "react";
import { publicModelPath } from "../../../../config/3d-model.config";
import { interactionGroups, RigidBody } from "@react-three/rapier";
import { CollisionWorldType } from "../../../../../config/collision";
import { BackSide, Mesh } from "three";
import CorridorLight from "./corridor-light";

type Props = JSX.IntrinsicElements["group"] & {};

const path = publicModelPath("high_build_corridor.glb");

export default function Corridor(props: Props) {
  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null} frustumCulled={true}>
      <CorridorLight />
      <RigidBody
        type="fixed"
        colliders="trimesh"
        collisionGroups={interactionGroups(CollisionWorldType.corridor)}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_wall002 as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_floor as Mesh).geometry}
          material={materials.floor_betton}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_wall as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_wall001 as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_ceiling as Mesh).geometry}
          material={materials.floor_betton}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_ceiling001 as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_wall003 as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.corridor_wall004 as Mesh).geometry}
          material={materials.Brownstone_Facade_Flr_2}
          position={[9.857, -24.036, 24.799]}
          scale={1.446}
          material-side={BackSide}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload(path);
