/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { JSX, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { publicModelPath } from "../../../config/3d-model.config";
import { Mesh, MeshStandardMaterial } from "three";
import { RigidBody } from "@react-three/rapier";
import { RotorModel } from "./rotor";
import InfoZone from "./zone-to-folio";
import { useEditModeStore } from "../../../store/useEditModeStore";
import { usePauseStore } from "../../../store/usePauseMode";

const path = publicModelPath("house_furniture.glb");

type Props = JSX.IntrinsicElements["group"] & {};

export default function HouseFurniture(props: Props) {
  const isEditModeEnabled = useEditModeStore((s) => s.isEditModeEnabled);
  const isGameStarted = usePauseStore((s) => s.isGameStarted);
  const { nodes, materials } = useGLTF(path);

  const { kernelMat, dreamMat } = useMemo(() => {
    const lampMat = (
      materials["cube_material.021"] as MeshStandardMaterial
    ).clone();
    lampMat.emissiveIntensity = 1.5;
    lampMat.roughness = 0.6;
    lampMat.metalness = 0.0;
    lampMat.toneMapped = false;

    const kernelMat = (
      materials["Material.016"] as MeshStandardMaterial
    ).clone();
    kernelMat.color.multiplyScalar(0.4); // 60% яскравості
    kernelMat.toneMapped = false;

    const dreamMat = (
      materials["Material.017"] as MeshStandardMaterial
    ).clone();
    dreamMat.color.multiplyScalar(1.3); // 60% яскравості
    dreamMat.toneMapped = false;

    return { lampMat, kernelMat, dreamMat };
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <RotorModel position={[-7.5, 0.2, 3]} scale={0.7} />
      <RigidBody type="dynamic" colliders="cuboid" lockRotations>
        <mesh
          geometry={(nodes.cup as Mesh).geometry}
          material={materials["cube_material.024"]}
          position={[-3.848, 2.161, 2.645]}
          rotation={[0, 0.407, 0]}
          scale={0.051}
        />
      </RigidBody>
      <mesh
        geometry={(nodes._cube_bottom012 as Mesh).geometry}
        material={materials.metalic}
        position={[-5.744, 1.233, 8.627]}
        rotation={[-3.009, -0.018, 3.101]}
        scale={[0.007, 0.009, 0.007]}
      />
      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          geometry={(nodes.table_drawer002 as Mesh).geometry}
          material={materials.table_bake}
        />
      </RigidBody>
      <mesh
        geometry={(nodes.table_drawer001 as Mesh).geometry}
        material={materials.table_bake}
      />
      <mesh
        geometry={(nodes.table_drawer003 as Mesh).geometry}
        material={materials.table_bake}
      />
      <mesh
        geometry={(nodes.table_drawer004 as Mesh).geometry}
        material={materials.table_bake}
      />
      <mesh
        geometry={(nodes._cube_bottom019 as Mesh).geometry}
        material={materials["Material.052"]}
        position={[-3.414, 1.232, 1.22]}
      />
      <group position={[-3.414, 1.232, 1.22]}>
        <mesh
          geometry={(nodes.Cube151 as Mesh).geometry}
          material={materials["cube_material.019"]}
        />
        <mesh
          geometry={(nodes.Cube151_1 as Mesh).geometry}
          material={materials["cube_material.020"]}
        />
      </group>
      <mesh
        geometry={(nodes.pc_system_button as Mesh).geometry}
        material={materials["Material.052"]}
        position={[-3.414, 1.232, 1.22]}
      />
      <mesh
        geometry={(nodes.pc_system_button_2 as Mesh).geometry}
        material={materials["Material.052"]}
        position={[-3.414, 1.232, 1.22]}
      />
      <RigidBody type="dynamic" colliders="cuboid">
        <group>
          <mesh
            geometry={(nodes.pc_monitor as Mesh).geometry}
            material={materials.pc_monitor_bake}
            position={[0.009, 0, 0.047]}
          />
          <mesh
            geometry={(nodes.pc_screen as Mesh).geometry}
            material={materials["Material.006"]}
            position={[0.009, 0, 0.047]}
          />
          <mesh
            geometry={(nodes.pc_monitor_light as Mesh).geometry}
            material={materials.pc_monitor_bake}
            position={[0.009, 0, 0.047]}
          />
          <mesh
            geometry={(nodes.pc_monitor_button as Mesh).geometry}
            material={materials.pc_monitor_bake}
            position={[0.009, 0, 0.047]}
          />
        </group>
      </RigidBody>
      <mesh
        geometry={(nodes._cube_bottom018 as Mesh).geometry}
        material={materials.keyboard}
        position={[-3.866, 2.135, 1.511]}
        rotation={[0, 0.581, 0]}
      />
      <mesh
        geometry={(nodes._cube_bottom028 as Mesh).geometry}
        material={materials["Material.050"]}
        position={[-3.727, 2.131, 1.805]}
        rotation={[0, 0.53, 0]}
        scale={[0.014, 0.002, 0.005]}
      />
      <mesh
        geometry={(nodes._cube_bottom029 as Mesh).geometry}
        material={materials["cube_material.018"]}
        position={[-3.704, 2.109, 1.799]}
        rotation={[0, 0.546, 0]}
        scale={[0.007, 0.003, 0.003]}
      />
      <RigidBody type="dynamic" colliders="hull" lockRotations ccd>
        <mesh
          geometry={(nodes._cube_bottom033 as Mesh).geometry}
          material={materials.laptop}
          position={[-3.831, 2.116, 2.189]}
          rotation={[0, 0.045, 0]}
        >
          <mesh
            geometry={(nodes._cube_bottom035 as Mesh).geometry}
            material={materials.laptop}
            position={[0.147, 0.013, -0.001]}
            rotation={[0, 0, 1.172]}
            scale={[0.156, 0.011, 0.192]}
          >
            <mesh
              geometry={(nodes.laptop_screen as Mesh).geometry}
              material={materials.laptop}
            />
          </mesh>
          <mesh
            geometry={(nodes._cube_bottom037 as Mesh).geometry}
            material={materials["Material.049"]}
            position={[0.064, 0.02, 0.014]}
            scale={[1.21, 0.64, 1.21]}
          />
        </mesh>
      </RigidBody>
      <RigidBody type="fixed" colliders="hull">
        <mesh
          geometry={(nodes._cube_bottom039 as Mesh).geometry}
          material={materials["cube_material.022"]}
          position={[-5.144, 2.061, 2.083]}
          rotation={[0, 0, -1.47]}
        />
      </RigidBody>
      <group
        position={[-3.61, 2.109, 2.726]}
        rotation={[0, 0.389, 0]}
        scale={[0.112, 0.02, 0.076]}
      >
        <mesh
          geometry={(nodes.Cube170 as Mesh).geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={(nodes.Cube170_1 as Mesh).geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={(nodes.Cube170_2 as Mesh).geometry}
          material={materials["Material.015"]}
        />
      </group>
      <group position={[-3.457, 2.109, 2.949]} scale={[0.112, 0.02, 0.076]}>
        <mesh
          geometry={(nodes.Cube171 as Mesh).geometry}
          material={materials["learn_three.js_webgl"]}
        />
        <mesh
          geometry={(nodes.Cube171_1 as Mesh).geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={(nodes.Cube171_2 as Mesh).geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        geometry={(nodes.kernel_logo as Mesh).geometry}
        material={materials.kernel_logo}
        position={[-6.136, 3.172, 0.994]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.067, 0.013, 0.133]}
      />
      <mesh
        geometry={(nodes.dream_logo as Mesh).geometry}
        material={materials["Material.018"]}
        position={[-3.135, 2.992, 3.819]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.067, 0.013, 0.133]}
      />
      <mesh
        geometry={(nodes.kernel_picture as Mesh).geometry}
        material={materials["cube_material.025"]}
        position={[-6.157, 2.623, 0.962]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.55, 0.022, 1.012]}
      />
      <mesh
        geometry={(nodes.kernel_picture001 as Mesh).geometry}
        material={kernelMat}
        position={[-6.157, 2.623, 0.981]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.518, 0.021, 0.953]}
      />
      <mesh
        geometry={(nodes._cube_bottom042 as Mesh).geometry}
        material={materials["cube_material.025"]}
        position={[-3.147, 2.662, 3.81]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.262, 0.022, 0.447]}
      />
      <mesh
        geometry={(nodes._cube_bottom043 as Mesh).geometry}
        material={dreamMat}
        position={[-3.152, 2.662, 3.81]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        geometry={(nodes.log026 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.103, 1.33, 8.8]}
        rotation={[-2.922, -0.908, 2.557]}
        scale={[0.023, 0.193, 0.023]}
      />
      <mesh
        geometry={(nodes.log001 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.268, 1.322, 8.899]}
        rotation={[3.072, -0.952, 2]}
        scale={[0.023, 0.193, 0.023]}
      />
      <mesh
        geometry={(nodes.log002 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.291, 1.351, 8.903]}
        rotation={[0.951, -0.349, -1.003]}
        scale={[0.023, 0.193, 0.023]}
      />
      <mesh
        geometry={(nodes.log003 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.066, 1.39, 8.879]}
        rotation={[0.534, 0.498, 1.234]}
        scale={[0.032, 0.193, 0.032]}
      />
      <mesh
        geometry={(nodes.log004 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.001, 1.461, 8.922]}
        rotation={[0.534, 0.498, 1.234]}
        scale={[0.032, 0.193, 0.032]}
      />
      <mesh
        geometry={(nodes.log005 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.384, 1.313, 8.855]}
        rotation={[0.579, -0.081, -0.318]}
        scale={[0.032, 0.193, 0.032]}
      />
      <mesh
        geometry={(nodes.log006 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-6.162, 1.621, 8.998]}
        rotation={[-2.721, -0.269, -0.504]}
        scale={[0.023, 0.193, 0.023]}
      />
      <mesh
        geometry={(nodes.log_dark as Mesh).geometry}
        material={materials["wood.003"]}
        position={[-6.233, 1.322, 8.923]}
        rotation={[-2.885, 0.325, -2.073]}
        scale={[0.021, 0.178, 0.021]}
      />
      <mesh
        geometry={(nodes.log_dark001 as Mesh).geometry}
        material={materials["wood.003"]}
        position={[-6.234, 1.315, 8.919]}
        rotation={[-1.946, -0.068, 2.422]}
        scale={[0.021, 0.178, 0.021]}
      />
      <mesh
        geometry={(nodes.log_dark002 as Mesh).geometry}
        material={materials["wood.003"]}
        position={[-6.257, 1.293, 8.86]}
        rotation={[-2.033, -0.021, -2.856]}
        scale={[0.021, 0.178, 0.021]}
      />

      <mesh
        geometry={(nodes.log011 as Mesh).geometry}
        material={materials["wood.002"]}
        position={[-7.125, 1.241, 8.49]}
        rotation={[2.697, 0.26, -1.609]}
        scale={[0.01, 0.062, 0.01]}
      />
      <RigidBody
        type="dynamic"
        colliders="hull"
        ccd
        restitution={0}
        friction={0.7}
      >
        <mesh
          geometry={(nodes.log009 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-6.661, 1.292, 8.219]}
          rotation={[-1.354, 0.548, 2.487]}
          scale={[0.032, 0.193, 0.032]}
        />

        <mesh
          geometry={(nodes.log010 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-7.062, 1.243, 8.405]}
          rotation={[3.077, 0.634, -2.007]}
          scale={[0.019, 0.116, 0.019]}
        />
        <mesh
          geometry={(nodes.log007 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-6.824, 1.281, 8.258]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.032, 0.193, 0.032]}
        />
        <mesh
          geometry={(nodes.log008 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-6.914, 1.276, 8.285]}
          rotation={[-Math.PI / 2, 0.663, -Math.PI]}
          scale={[0.032, 0.193, 0.032]}
        />
        <mesh
          geometry={(nodes.log012 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-6.614, 1.281, 8.579]}
          rotation={[-1.646, 0.144, 0.011]}
          scale={[0.03, 0.123, 0.03]}
        />
        <mesh
          geometry={(nodes.log013 as Mesh).geometry}
          material={materials["wood.002"]}
          position={[-6.682, 1.283, 8.574]}
          rotation={[1.824, -0.702, 2.968]}
          scale={[0.03, 0.123, 0.03]}
        />
      </RigidBody>
      <mesh
        geometry={(nodes.Plane008 as Mesh).geometry}
        material={materials["Material.028"]}
        position={[-6.997, 3.755, 0.981]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.143}
      />
      <mesh
        geometry={(nodes.Text003 as Mesh).geometry}
        material={materials["Material.029"]}
        position={[-7.246, 3.455, 0.987]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.166}
      />
      <mesh
        geometry={(nodes.kernel_picture002 as Mesh).geometry}
        material={materials["Material.051"]}
        position={[-3.145, 3.664, 2.37]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture003 as Mesh).geometry}
        material={materials["Material.053"]}
        position={[-4.378, 3.68, 0.969]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture004 as Mesh).geometry}
        material={materials["Material.054"]}
        position={[-3.145, 3.662, 2.929]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture005 as Mesh).geometry}
        material={materials["Material.055"]}
        position={[-3.136, 3.786, 4.734]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.174, 0.007, 0.136]}
      />
      <mesh
        geometry={(nodes.kernel_picture006 as Mesh).geometry}
        material={materials["Material.056"]}
        position={[-3.135, 3.788, 5.471]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.174, 0.007, 0.136]}
      />
      <mesh
        geometry={(nodes.kernel_picture007 as Mesh).geometry}
        material={materials["Material.057"]}
        position={[-3.841, 3.681, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture008 as Mesh).geometry}
        material={materials["Material.058"]}
        position={[-3.147, 3.788, 5.108]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.176, 0.007, 0.137]}
      />
      <mesh
        geometry={(nodes.kernel_picture009 as Mesh).geometry}
        material={materials["Material.059"]}
        position={[-4.922, 3.679, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture010 as Mesh).geometry}
        material={materials["Material.060"]}
        position={[-5.455, 3.677, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture011 as Mesh).geometry}
        material={materials["Material.061"]}
        position={[-6.498, 3.677, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture012 as Mesh).geometry}
        material={materials["Material.062"]}
        position={[-7.491, 3.677, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture013 as Mesh).geometry}
        material={materials["Material.063"]}
        position={[-8.028, 3.677, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture014 as Mesh).geometry}
        material={materials["Material.064"]}
        position={[-8.564, 3.677, 0.978]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.313, 0.012, 0.244]}
      />
      <mesh
        geometry={(nodes.kernel_picture015 as Mesh).geometry}
        material={materials["Material.065"]}
        position={[-3.152, 3.678, 1.722]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.225, 0.009, 0.175]}
      />
      <mesh
        geometry={(nodes.kernel_picture016 as Mesh).geometry}
        material={materials["Material.066"]}
        position={[-3.139, 3.679, 1.263]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.225, 0.009, 0.175]}
      />
      <mesh
        geometry={(nodes.kernel_picture017 as Mesh).geometry}
        material={materials["Material.067"]}
        position={[-3.142, 3.662, 3.483]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.315, 0.013, 0.246]}
      >
        <group
          position={[0.219, -0.621, 0.034]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.679, 13.321, 0.529]}
        >
          <mesh
            geometry={(nodes.Text005 as Mesh).geometry}
            material={(nodes.Text005 as Mesh).material}
          />
          <mesh
            geometry={(nodes.Text005_1 as Mesh).geometry}
            material={materials["cube_material.032"]}
          />
        </group>
      </mesh>
      <mesh
        geometry={(nodes.kernel_picture018 as Mesh).geometry}
        material={materials["Material.068"]}
        position={[-3.136, 3.786, 4.38]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.174, 0.007, 0.136]}
      />
      <mesh
        geometry={(nodes.kernel_picture019 as Mesh).geometry}
        material={materials["Material.069"]}
        position={[-3.147, 2.667, 5.981]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.366, 0.015, 0.286]}
      />
      <mesh
        geometry={(nodes.kernel_picture020 as Mesh).geometry}
        material={materials["Material.070"]}
        position={[-3.147, 3.249, 5.981]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.218, 0.009, 0.17]}
      />
      <RigidBody type="fixed" colliders="hull">
        <mesh
          geometry={(nodes.earth as Mesh).geometry}
          material={materials["Material.045"]}
          position={[-3.413, 2.005, 6.015]}
          rotation={[2.931, 0.599, -2.88]}
          scale={0.223}
        />
        <mesh
          geometry={(nodes.moon as Mesh).geometry}
          material={materials["Material.046"]}
          position={[-3.321, 2.256, 5.78]}
          rotation={[-0.078, 0.146, -0.262]}
          scale={0.054}
        />
        <group position={[-3.417, 1.233, 5.999]} scale={[0.093, 0.009, 0.093]}>
          <mesh
            geometry={(nodes.Cube241 as Mesh).geometry}
            material={materials["cube_material.039"]}
          />
          <mesh
            geometry={(nodes.Cube241_1 as Mesh).geometry}
            material={materials["cube_material.038"]}
          />
        </group>
      </RigidBody>
      {(!isEditModeEnabled || isGameStarted) && (
        <InfoZone position={[-6.082, 1.239, 4.838]} size={[4.9, 2, 3]} />
      )}

      <mesh
        geometry={(nodes.Plane009 as Mesh).geometry}
        material={materials["Material.071"]}
        position={[-6.082, 1.239, 4.838]}
        scale={[2.452, 1.519, 1.519]}
      />
      {/* lamps */}
      {/* <mesh
        geometry={(nodes._cube_bottom004 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-7.594, 4.056, 0.965]}
        rotation={[Math.PI / 2, -1.571, 0]}
        scale={[0.029, 0.029, 0.468]}
      />
      <mesh
        geometry={(nodes._cube_bottom027 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-4.666, 4.056, 0.965]}
        rotation={[Math.PI / 2, -1.571, 0]}
        scale={[0.029, 0.029, 0.468]}
      />
      <mesh
        geometry={(nodes._cube_bottom038 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-3.128, 4.042, 2.918]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.029, 0.029, 0.468]}
      />
      <mesh
        geometry={(nodes._cube_bottom041 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-3.128, 3.964, 1.489]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.019, 0.019, 0.192]}
      />
      <mesh
        geometry={(nodes._cube_bottom046 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-3.128, 4.042, 4.895]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.029, 0.029, 0.468]}
      />
      <mesh
        geometry={(nodes._cube_bottom093 as Mesh).geometry}
        material={lampMat}
        castShadow
        position={[-3.162, 3.545, 5.98]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[0.024, 0.024, 0.193]}
      /> */}
    </group>
  );
}

useGLTF.preload(path);
