/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { JSX, useEffect, useRef } from "react";
import { publicModelPath } from "../../../config/3d-model.config";
import { Mesh } from "three";
import {
  interactionGroups,
  RapierRigidBody,
  RigidBody,
  useRevoluteJoint,
} from "@react-three/rapier";
import { CollisionWorldType } from "../../../../config/collision";

type Props = JSX.IntrinsicElements["group"] & {};

const path = publicModelPath("own_house.glb");

export default function OwnHouse(props: Props) {
  const { nodes, materials } = useGLTF(path);
  const frameRef = useRef<RapierRigidBody>(null!); // нерухома рама
  const doorRef = useRef<RapierRigidBody>(null!); // динамічні двері

  const joint = useRevoluteJoint(frameRef, doorRef, [
    [0, 0, 0],
    [0, 0, 0],
    [0, 1, 0],
  ]);

  useEffect(() => {
    if (joint.current) {
      joint.current.setLimits(-Math.PI / 2, Math.PI / 2);
    }
  }, [joint]);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes._cube_bottom020 as Mesh).geometry}
        material={materials.house_wood}
        position={[-6.023, -0.176, 4.877]}
        scale={[3.922, 3.922, 4.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes._cube_bottom021 as Mesh).geometry}
        material={materials.house_wood}
        position={[-6.022, -0.176, 4.877]}
        scale={[3.922, 3.922, 4.052]}
      />
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom004 as Mesh).geometry}
          material={materials.roof}
          position={[-6.023, -0.176, 4.877]}
          scale={[3.922, 3.922, 4.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.roof as Mesh).geometry}
          material={materials.roof}
          position={[-6.023, 0.361, 4.877]}
          scale={3.922}
        />
      </RigidBody>
      <group position={[-3.1, 1.13, 4.34]}>
        <RigidBody
          ref={frameRef}
          type="fixed"
          colliders={false}
          position={[0, 0.14, 0]}
        />
        <RigidBody
          ref={doorRef}
          colliders="hull"
          position={[0, 0.16, 0]}
          collisionGroups={interactionGroups(CollisionWorldType.doorHouse, [
            CollisionWorldType.mainCharacter,
          ])}
          mass={0}
          friction={0}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes._cube_bottom025 as Mesh).geometry}
            material={materials.door_wood}
            rotation={[-Math.PI, Math.PI, -Math.PI]}
            scale={[0.256, 1.111, 0.597]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes._cube_bottom006 as Mesh).geometry}
              material={materials["cube_material.004"]}
              position={[-0.136, 0.97, 1.631]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.037, 0.008, 0.016]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes._cube_bottom026 as Mesh).geometry}
              material={materials["cube_material.004"]}
              position={[0.123, 0.918, 1.631]}
              scale={[0.037, 0.008, 0.016]}
            />
          </mesh>
        </RigidBody>
      </group>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom022 as Mesh).geometry}
          material={materials.roof}
          position={[-6.026, -0.176, 4.877]}
          scale={[3.922, 3.922, 4.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.597, -0.174, 1.027]}
          scale={0.157}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom002 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-1.932, 1.248, 1.018]}
          scale={[1.181, 0.013, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom005 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.597, -0.174, 3.75]}
          scale={0.157}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom008 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.597, -0.174, 6.095]}
          scale={0.157}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom009 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.597, -0.174, 8.679]}
          scale={0.157}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom011 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.671, 1.248, 2.368]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.242, 0.013, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom015 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-1.932, 1.983, 8.737]}
          scale={[1.181, 0.013, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom017 as Mesh).geometry}
          material={materials["wood.001"]}
          position={[-0.671, 1.248, 7.39]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.242, 0.013, 0.049]}
        />
      </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.sdie_hose as Mesh).geometry}
        material={materials.house_wood}
        position={[-6.023, -0.176, 4.877]}
        scale={3.922}
      >
        <group
          position={[0.565, 1.914, 0.022]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.092}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube125 as Mesh).geometry}
            material={materials["cube_material.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube125_1 as Mesh).geometry}
            material={materials["cube_material.011"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses012 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0.012, 1.92, -0.006]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={0.912}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window001 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[-0.495, 0.713, -0.997]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses001 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0, 0.003, -0.002]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window002 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.411, 0.713, -0.997]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0, 0.003, 0.012]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window004 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.411, 1.476, -0.997]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses003 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0.016, 0.003, -0.001]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window006 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[-0.495, 1.476, -0.997]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses002 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0.016, 0.003, -0.002]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window009 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.411, 0.713, 1.005]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses004 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0, 0.093, 0.012]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window010 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[-0.495, 0.713, 1.005]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses005 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0, 0.093, -0.002]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window013 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.411, 1.476, 1.005]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses007 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0.016, 0.093, -0.001]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window014 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[-0.495, 1.476, 1.005]}
          rotation={[-Math.PI / 2, -1.571, 0]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses006 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[0.016, 0.093, -0.002]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
      </mesh>
      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom001 as Mesh).geometry}
          material={materials["bricks.001"]}
          position={[-6.023, -0.176, 4.877]}
          scale={3.922}
        />
      </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.front_box_side as Mesh).geometry}
        material={materials.house_wood}
        position={[-6.023, -0.176, 4.877]}
        scale={3.922}
      >
        <RigidBody
          type="fixed"
          colliders="trimesh"
          collisionGroups={interactionGroups(CollisionWorldType.doorFrame)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes._cube_bottom024 as Mesh).geometry}
            material={materials.cube_material}
            position={[0.744, 0.635, 0.005]}
            scale={[0.198, 0.283, 0.152]}
          />
        </RigidBody>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window017 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.733, 1.484, 0.451]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses010 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[-0.034, 0.014, 0.053]}
            rotation={[-Math.PI, 0, 0]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.first_side_window018 as Mesh).geometry}
          material={materials["cube_material.009"]}
          position={[0.733, 1.484, -0.455]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[0.151, 0.097, 0.151]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses011 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[-0.034, 0.014, 0.052]}
            rotation={[-Math.PI, 0, 0]}
            scale={[0.958, 1.501, 0.958]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.front_window as Mesh).geometry}
          material={materials["cube_material.006"]}
          position={[0.74, 0.56, -0.643]}
          scale={[0.008, 0.163, 0.247]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses008 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[-0.376, 0.981, -0.002]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.93, 17.293, 0.908]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.front_window001 as Mesh).geometry}
          material={materials["cube_material.006"]}
          position={[0.74, 0.56, 0.643]}
          scale={[0.008, 0.163, 0.247]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.window_glasses009 as Mesh).geometry}
            material={materials["Material.002"]}
            position={[-0.376, 0.981, 0.002]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.93, 17.293, 0.908]}
          />
        </mesh>
      </mesh>

      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={(nodes.front_box_side_collider as Mesh).geometry}
          material-visible={false}
          position={[-6.023, -0.176, 4.877]}
          scale={3.922}
        />
        <mesh
          geometry={(nodes.sdie_hose_collider as Mesh).geometry}
          material-visible={false}
          position={[-6.023, -0.176, 4.877]}
          scale={3.922}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.ftont_floor as Mesh).geometry}
          material={materials.parket}
          position={[-6.023, -0.176, 4.877]}
          scale={3.922}
        />
      </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stairs_side as Mesh).geometry}
        material={materials["bricks.001"]}
        position={[0.386, -0.171, 4.926]}
        scale={[1, 0.682, 1]}
      />
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.stairs_floor as Mesh).geometry}
          material={materials.parket}
          position={[0.386, -0.171, 4.926]}
          scale={[1, 0.682, 1]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="hull">
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes._cube_bottom014 as Mesh).geometry}
          material={materials.parket}
          position={[-6.53, 1.093, 4.881]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-3.424, -0.07, -3.916]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="cuboid">
        <group position={[-6.206, -0.175, 9.096]} scale={[0.574, 3.998, 0.381]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube074 as Mesh).geometry}
            material={materials["bricks.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube074_1 as Mesh).geometry}
            material={materials.groub}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube074_2 as Mesh).geometry}
            material={materials["black.002"]}
          />
        </group>
      </RigidBody>
    </group>
  );
}

useGLTF.preload(path);
