export enum ExperimentalTypes {
  physics = "physics",
  shaders = "shaders",
  camera = "camera",
  games = "games",
  webgpu = "webgpu",
  ai = "ai",
  particle = "particle",
  maps = "maps",
  canvas2d = "2d-canvas",
  vfx = "vfx",
  particles = "particles",
  optimization = "optimization",
  yuka = "yuka",
  raycast = "raycast-navigation",
  baking = "baking-texture",
  demoScenes = "demo-scenes",
}
