export enum Key {
  G = "KeyG",
  S = "KeyS",
  R = "KeyR",
  X = "KeyX",
  D = "KeyD",
  C = "KeyC",
  V = "KeyV",
  A = "KeyA",
  P = "KeyP",
  ESC = "Escape",
  ENTER = "Enter",
  SPACE = "Space",
  shiftLeft = "shiftLeft",
}
