/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { JSX, useRef } from "react";
import { publicModelPath } from "../../../config/3d-model.config";
import { Group, Mesh, MeshBasicMaterial, MeshStandardMaterial } from "three";
import CampfireCollider from "./campfire-collider";
import { useFrame } from "@react-three/fiber";
import FireParticle from "./fire-particle";

type Props = JSX.IntrinsicElements["group"] & {};

const path = publicModelPath("campfire.glb");

export function Campfire({ ...props }: Props) {
  const { nodes } = useGLTF(path);
  const cookingPotRef = useRef<Group>(null);
  const woodMaterial = new MeshStandardMaterial({
    color: "#FF9455",
  });
  const woodBurnedMaterial = new MeshStandardMaterial({
    color: "#22140B",
  });
  const potMetallicMaterial = new MeshStandardMaterial({
    color: "#AFABAD",
    metalness: 0.7,
    roughness: 0.2,
  });
  const ropMetallicMaterial = new MeshStandardMaterial({
    color: "#AF936D",
    metalness: 0.6,
    roughness: 0.6,
  });

  const stoneMaterial = new MeshStandardMaterial({
    color: "#C6C1C4",
    metalness: 0.1,
    roughness: 0.7,
  });

  const tRef = useRef(0);
  const base = useRef<{ x: number; y: number; z: number }>({
    x: 0,
    y: 0,
    z: 0,
  });

  useFrame((_, dt) => {
    if (!cookingPotRef.current) return;

    tRef.current += dt; // ← накопичуємо час
    const t = tRef.current;

    const f = 0.3; // частота (циклів/с)
    const w = 2 * Math.PI * f; // кутова частота
    const gust = 0.7 + 0.3 * Math.sin(t * 0.2); // повільна «пульсація вітру»

    const ampX = 0.12; // ~7°
    const ampZ = 0.09; // ~3.5°

    const rx = base.current.x + Math.sin(w * t) * ampX * gust;
    const rz = base.current.z + Math.sin(w * t + Math.PI / 3) * ampZ * gust;

    cookingPotRef.current.rotation.y = rx;
    cookingPotRef.current.rotation.z = rz;
  });

  const blackMaterial = new MeshBasicMaterial({ color: "black" });
  return (
    <group {...props} dispose={null}>
      <FireParticle position={[-0.2, -0.9, -0.1]} />
      <CampfireCollider />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log004 as Mesh).geometry}
        material={woodMaterial}
        position={[2.527, -0.051, 1.044]}
        rotation={[-Math.PI, 0.131, -Math.PI]}
        scale={[0.026, 0.559, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log005 as Mesh).geometry}
        material={woodMaterial}
        position={[2.269, 0, 2.274]}
        rotation={[Math.PI, -0.07, Math.PI]}
        scale={[0.026, 0.528, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log006 as Mesh).geometry}
        material={woodMaterial}
        position={[2.267, 1.083, 2.384]}
        rotation={[-0.006, 1.372, -1.556]}
        scale={[0.026, 0.743, 0.026]}
      />
      <group
        ref={cookingPotRef}
        position={[2.415, 1.091, 1.668]}
        rotation={[0, 1.312, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cube038 as Mesh).geometry}
          material={potMetallicMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cube038_1 as Mesh).geometry}
          material={blackMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cube038_2 as Mesh).geometry}
          material={ropMetallicMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log007 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.175, 0, 1.465]}
        rotation={[1.641, 0.972, -1.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log008 as Mesh).geometry}
        material={woodMaterial}
        position={[2.211, 0, 1.354]}
        rotation={[1.206, 0.851, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log009 as Mesh).geometry}
        material={woodMaterial}
        position={[2.07, 0, 1.68]}
        rotation={[-0.543, -0.716, -0.846]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log010 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.086, 0, 1.541]}
        rotation={[1.321, 0.36, -1.146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log011 as Mesh).geometry}
        material={woodMaterial}
        position={[2.538, 0, 1.365]}
        rotation={[0.48, 0.098, 0.363]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log012 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.681, 0, 1.407]}
        rotation={[0.324, 0.559, 0.789]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log013 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.303, 0, 1.32]}
        rotation={[-1.762, -0.676, -2.705]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log014 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.442, 0, 1.3]}
        rotation={[1.284, -0.108, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log015 as Mesh).geometry}
        material={woodMaterial}
        position={[2.686, 0, 1.813]}
        rotation={[2.393, -0.806, 2.529]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log016 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.593, 0.011, 1.825]}
        rotation={[1.283, -0.413, 2.211]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log017 as Mesh).geometry}
        material={woodMaterial}
        position={[2.768, 0, 1.588]}
        rotation={[-2.456, 0.532, 2.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log018 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.766, 0, 1.728]}
        rotation={[1.886, -0.436, 1.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log019 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.234, 0, 1.899]}
        rotation={[1.737, 0.082, -2.902]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log020 as Mesh).geometry}
        material={woodMaterial}
        position={[2.124, 0, 1.863]}
        rotation={[2.556, 0.431, -2.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log021 as Mesh).geometry}
        material={woodMaterial}
        position={[2.503, 0, 1.999]}
        rotation={[-0.762, 0.747, 0.198]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.log022 as Mesh).geometry}
        material={woodBurnedMaterial}
        position={[2.31, 0, 1.987]}
        rotation={[2.225, 0.16, -2.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone001 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.143, 0, 1.257]}
        rotation={[0.007, -0.728, 0.001]}
        scale={[1.011, 0.999, 0.984]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone002 as Mesh).geometry}
        material={stoneMaterial}
        position={[1.994, 0, 1.537]}
        rotation={[0.005, 0.262, -0.096]}
        scale={[0.99, 1.019, 1.033]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone004 as Mesh).geometry}
        material={stoneMaterial}
        position={[1.994, 0, 1.711]}
        rotation={[-0.007, 0.758, -0.143]}
        scale={[0.999, 0.997, 0.968]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone006 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.791, 0, 1.39]}
        rotation={[3.139, -1.318, 3.004]}
        scale={[1.012, 0.981, 1.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone007 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.505, 0, 1.257]}
        rotation={[-0.006, -0.865, 0.18]}
        scale={[1.015, 0.993, 0.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone008 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.38, 0, 1.223]}
        rotation={[0.009, -0.814, -0.167]}
        scale={[0.998, 0.993, 0.966]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone009 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.63, 0, 2.076]}
        rotation={[-3.14, 0.461, 3.064]}
        scale={[1.013, 1.019, 1.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone010 as Mesh).geometry}
        material={stoneMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone011 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.843, 0, 1.638]}
        rotation={[3.129, -0.734, 3.038]}
        scale={[1.017, 1.016, 1.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone012 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.014, 0, 1.906]}
        rotation={[-0.06, 1.492, 0.143]}
        scale={[1.014, 1.004, 1.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone013 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.238, 0, 2.075]}
        rotation={[-3.132, 1.164, 2.949]}
        scale={[1.012, 1.005, 0.967]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.stone014 as Mesh).geometry}
        material={stoneMaterial}
        position={[2.397, 0, 2.075]}
        rotation={[0.007, 0.532, -0.089]}
        scale={[0.989, 0.993, 1.024]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes._cube_bottom017 as Mesh).geometry}
        material={blackMaterial}
        position={[2.42, 0, 1.668]}
        rotation={[0, 1.312, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes._cube_bottom016 as Mesh).geometry}
        material={blackMaterial}
        position={[2.457, 0, 1.441]}
        rotation={[0, 1.312, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes._cube_bottom019 as Mesh).geometry}
        material={blackMaterial}
        position={[2.352, 0, 1.882]}
        rotation={[0, 1.312, 0]}
      />
    </group>
  );
}

useGLTF.preload(path);
