export const AGENT_COUNT = 5;
export const RADIUS = 1.2;
export const HEIGHT = 4.4;
export const BODY_Y_OFFSET = HEIGHT / 2;
export const PATH_HALF_EXTENTS = { x: 15, y: 15, z: 15 };
export const AGENT_SPEED = 3.5;
export const PATH_UPDATE_INTERVAL_MS = 1000;
export const WAYPOINT_REACH_DIST = 0.5;
export const STOP_DIST_TO_PLAYER = 2;
