/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { publicModelPath } from "../../../config/3d-model.config";
import { Mesh } from "three";
import { RigidBody } from "@react-three/rapier";

type Props = JSX.IntrinsicElements["group"] & {};

const path = publicModelPath("tent_collider.glb");

export function TentCollider({ ...props }: Props) {
  const { nodes } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <RigidBody userData={{ isGround: true }} type="fixed" colliders="trimesh">
        <mesh
          geometry={(nodes.tent_collider as Mesh).geometry}
          material-visible={false}
          position={[3.669, 0, -2.903]}
          rotation={[0.68, 1.175, -0.852]}
          scale={[0.019, 0.12, 0.019]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          geometry={(nodes.tent_log as Mesh).geometry}
          material-visible={false}
          position={[3.704, 0.114, -2.919]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_log001 as Mesh).geometry}
          material-visible={false}
          position={[0.032, 0.116, -2.458]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_log002 as Mesh).geometry}
          material-visible={false}
          position={[-0.154, 0.114, -5.864]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_log003 as Mesh).geometry}
          material-visible={false}
          position={[3.327, 0.112, -6.27]}
          rotation={[0.68, 1.175, -0.852]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="hull">
        <mesh
          geometry={(nodes.tent_rope as Mesh).geometry}
          material-visible={false}
          position={[3.401, 0.308, -2.916]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_rope001 as Mesh).geometry}
          material-visible={false}
          position={[3.035, 0.308, -6.185]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_rope002 as Mesh).geometry}
          material-visible={false}
          position={[0.087, 0.298, -5.883]}
          rotation={[0.68, 1.175, -0.852]}
        />
        <mesh
          geometry={(nodes.tent_rope003 as Mesh).geometry}
          material-visible={false}
          position={[0.372, 0.311, -2.589]}
          rotation={[0.68, 1.175, -0.852]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload(path);
